-- MySQL Script generated by MySQL Workbench
-- Mon May  7 13:24:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema chattingonline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chattingonline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chattingonline` DEFAULT CHARACTER SET utf8 ;
USE `chattingonline` ;

-- -----------------------------------------------------
-- Table `chattingonline`.`t_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chattingonline`.`t_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(32) NOT NULL,
  `name` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unindex_user_id` (`id` ASC),
  UNIQUE INDEX `unindex_user_account` (`account` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chattingonline`.`t_friend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chattingonline`.`t_friend` (
  `owner_id` INT(11) NOT NULL,
  `friend_id` INT(11) NOT NULL,
  PRIMARY KEY (`owner_id`, `friend_id`),
  INDEX `fk_friend_friendId_user_id` (`friend_id` ASC),
  CONSTRAINT `fk_friend_friendId_user_id`
    FOREIGN KEY (`friend_id`)
    REFERENCES `chattingonline`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friend_ownerId_user_id`
    FOREIGN KEY (`owner_id`)
    REFERENCES `chattingonline`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chattingonline`.`t_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chattingonline`.`t_group` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `harem_master` INT(11) NOT NULL,
  `announcement` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_group_haremMaster_user_id` (`harem_master` ASC),
  CONSTRAINT `fk_group_haremMaster_user_id`
    FOREIGN KEY (`harem_master`)
    REFERENCES `chattingonline`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chattingonline`.`t_message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chattingonline`.`t_message` (
  `id` INT(11) NOT NULL,
  `from_id` INT(11) NOT NULL,
  `to_id` INT(11) NOT NULL,
  `send_time` DATETIME NOT NULL,
  `content` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`, `from_id`, `to_id`),
  INDEX `fk_message_fromId_user_id` (`from_id` ASC),
  INDEX `fk_message_toId_user_id` (`to_id` ASC),
  CONSTRAINT `fk_message_fromId_user_id`
    FOREIGN KEY (`from_id`)
    REFERENCES `chattingonline`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_toId_user_id`
    FOREIGN KEY (`to_id`)
    REFERENCES `chattingonline`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chattingonline`.`t_password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chattingonline`.`t_password` (
  `user_id` INT(11) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_password_userId_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `chattingonline`.`t_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chattingonline`.`t_user_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chattingonline`.`t_user_group` (
  `user_id` INT(11) NOT NULL,
  `group_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `group_id`),
  INDEX `fk_userGroup_groupId_user_id` (`group_id` ASC),
  CONSTRAINT `fk_userGroup_groupId_user_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `chattingonline`.`t_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userGroup_userId_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `chattingonline`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `chattingonline`.`t_user_information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chattingonline`.`t_user_information` (
  `user_id` INT(11) NOT NULL,
  `gender` VARCHAR(8) NULL DEFAULT NULL,
  `age` INT(11) NULL DEFAULT NULL,
  `birth` DATE NULL DEFAULT NULL,
  `address` VARCHAR(256) NULL DEFAULT NULL,
  `head_portrait` VARCHAR(256) NULL DEFAULT NULL,
  `e_mail` VARCHAR(128) NULL DEFAULT NULL,
  `phone` VARCHAR(11) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_userInformation_userId_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `chattingonline`.`t_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
